"""Offline reader for Atomic's retained native delegation evaluation, version 1.

Hashes bind a consumer selection to bytes. They establish neither issuer trust
nor independent capture. This reader never launches the retained executable.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
from pathlib import Path


CASES = (
    "exact_retry_and_process_restart_preserve_a_narrow_grant",
    "revocation_survives_restart_and_does_not_revoke_a_distinct_renewal",
    "expired_and_corrupt_grants_stay_inactive_after_restart",
    "local_selection_does_not_establish_external_issuer_authority",
)
SOURCE_FILES = (
    "source/Cargo.lock",
    "source/atomic-canonical/tests/delegation_restart.rs",
    "source/tools/native-evaluation/run.py",
    "source/tools/native-evaluation/README.md",
    "source/.github/workflows/ci.yml",
)
COVERAGE = {
    "boundary": "local persisted certificate selection in distinct OS processes",
    "keys": "ephemeral keys generated by the same operator; private keys are not retained",
    "clock": "local OS clock, with expiry controls one day away from the test time",
    "filesystem": "operator-owned temporary identity store",
    "server_authorization": "not established",
    "remote_revocation": "not established",
    "external_effects": "not observed",
    "crash_mid_write": "not evaluated",
    "model_execution": "not used",
}
SCOPE = {
    "permissions": ["record"], "projects": ["acme/project"],
    "servers": ["https://staging.example.test"], "views": ["review/*"],
    "workspaces": [],
}
SELECTION = "probity-atomic-native-selection/v1"
REPORT = "atomic-native-delegation-evaluation/v1"
MAX_JSON = 8 * 1024 * 1024
MAX_ARTIFACT = 256 * 1024 * 1024


def require(condition: bool, reason: str) -> None:
    if not condition:
        raise ValueError(reason)


def _pairs(pairs: list) -> dict:
    result = {}
    for key, value in pairs:
        require(key not in result, "duplicate_json_member")
        result[key] = value
    return result


def _float(value: str) -> float:
    result = float(value)
    require(math.isfinite(result), "nonfinite_json")
    return result


def decode(raw: bytes) -> dict:
    require(0 < len(raw) <= MAX_JSON, "json_size")
    result = json.loads(
        raw, object_pairs_hook=_pairs, parse_float=_float,
        parse_constant=lambda _: require(False, "nonfinite_json"),
    )
    require(type(result) is dict, "json_object")
    return result


def _json_raw(path: Path) -> bytes:
    require(path.is_file() and 0 < path.stat().st_size <= MAX_JSON, "json_size_or_missing")
    return path.read_bytes()


def sha(path: Path) -> str:
    require(path.is_file() and path.stat().st_size <= MAX_ARTIFACT, "artifact_size_or_missing")
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _plain(path: Path) -> Path:
    value = path.absolute()
    require(value.resolve() == value, "symlink_or_noncanonical_path")
    return value


def _digest(value: object) -> bool:
    return type(value) is str and re.fullmatch("[0-9a-f]{64}", value) is not None


def _file(packet: Path, name: str) -> Path:
    require(type(name) is str and bool(name), "artifact_name")
    relative = Path(name)
    require(not relative.is_absolute() and all(p not in (".", "..") for p in relative.parts), "artifact_path")
    require(relative.as_posix() == name, "artifact_path")
    return _plain(packet / relative)


def describe(packet: Path) -> dict:
    """Describe producer bytes for review; the result is not a trust decision."""
    packet = _plain(packet)
    raw = _json_raw(_file(packet, "report.json"))
    report = decode(raw)
    return {
        "schema": SELECTION,
        "source_commit": report["source"]["commit"],
        "report_sha256": hashlib.sha256(raw).hexdigest(),
        "reader_sha256": sha(Path(__file__).resolve()),
        "artifacts": {
            name: {"sha256": sha(_file(packet, name)), "bytes": _file(packet, name).stat().st_size}
            for name in report["artifacts"]
        },
    }


def _finished(result: dict) -> None:
    require(type(result) is dict, "native_process_shape")
    require(type(result.get("returncode")) is int and result["returncode"] == 0
            and result.get("timed_out") is False, "native_process_failed")
    seconds = result.get("wall_seconds")
    require(type(seconds) in (int, float) and 0 <= seconds <= 3600
            and math.isfinite(seconds), "wall_seconds")


def _observations(number: int, values: list) -> None:
    shapes = (
        ((1, 1, 0, True), (1, 1, 0, True)),
        ((1, 1, 0, True), (1, 1, 1, False), (2, 2, 1, True), (2, 2, 1, True)),
        ((1, 1, 0, False), (3, 1, 0, False), (3, 1, 0, False), (4, 2, 0, True)),
        ((1, 1, 0, True), (2, 1, 0, True)),
    )[number]
    require(type(values) is list and len(values) == len(shapes), "observation_population")
    expected_fields = {"pid", "stored", "verified_for_delegate", "locally_revoked", "active_id", "scope",
                       "allows_record", "allows_push", "allows_staging", "allows_production",
                       "allows_other_project", "allows_other_view", "coverage"}
    pids = set()
    for value, (stored, verified, revoked, active) in zip(values, shapes, strict=True):
        require(type(value) is dict and set(value) == expected_fields, "observation_fields")
        require(type(value["pid"]) is int and value["pid"] > 0 and value["pid"] not in pids, "worker_pid_population")
        pids.add(value["pid"])
        for key, expected in (("stored", stored), ("verified_for_delegate", verified), ("locally_revoked", revoked)):
            require(type(value[key]) is int and value[key] == expected, "native_store_control")
        require(value["coverage"] == "local-store-selection-only", "observation_coverage")
        for key in ("allows_push", "allows_production", "allows_other_project", "allows_other_view"):
            require(value[key] is False, "scope_widened")
        require(value["allows_record"] is active and value["allows_staging"] is active, "scope_positive_control")
        require(value["scope"] == (SCOPE if active else None), "scope_control")
        if active:
            require(type(value["active_id"]) is str
                    and re.fullmatch("[A-Z2-7]{52}", value["active_id"]) is not None, "grant_identifier")
        else:
            require(value["active_id"] is None, "inactive_grant_control")
    if number in (0, 3):
        require(values[0]["active_id"] == values[1]["active_id"], "retry_or_subject_control")
    if number == 1:
        require(values[0]["active_id"] != values[2]["active_id"]
                and values[2]["active_id"] == values[3]["active_id"], "renewal_control")


def verify(packet: Path, selection: Path, selection_sha256: str) -> dict:
    """Check selected bytes and native control records without rerunning Atomic."""
    packet, selection = _plain(packet), _plain(selection)
    require(not selection.is_relative_to(packet), "selection_inside_packet")
    selection_raw = _json_raw(selection)
    require(_digest(selection_sha256) and hashlib.sha256(selection_raw).hexdigest() == selection_sha256, "selection_pin_mismatch")
    selected = decode(selection_raw)
    require(set(selected) == {"schema", "source_commit", "report_sha256", "reader_sha256", "artifacts"}
            and selected["schema"] == SELECTION, "selection_fields")
    require(selected["reader_sha256"] == sha(Path(__file__).resolve()), "installed_reader_pin_mismatch")
    report_raw = _json_raw(_file(packet, "report.json"))
    require(_digest(selected["report_sha256"])
            and hashlib.sha256(report_raw).hexdigest() == selected["report_sha256"], "report_pin_mismatch")
    report = decode(report_raw)
    require(report.get("schema") == REPORT, "native_schema")
    require(type(report.get("source")) is dict
            and re.fullmatch("[0-9a-f]{40}", str(selected["source_commit"])) is not None
            and report["source"]["commit"] == selected["source_commit"]
            and report["source"]["status"] == "", "source_commit_or_dirty")
    require(report.get("coverage") == COVERAGE, "coverage_changed")
    binary = report.get("binary")
    require(type(binary) is dict and set(binary) == {"sha256", "filename"}
            and type(binary["filename"]) is str
            and re.fullmatch("delegation_restart-[a-zA-Z0-9_-]+", binary["filename"]) is not None
            and _digest(binary["sha256"]), "native_binary")
    expected_names = set(SOURCE_FILES) | {"source.diff", "build.stdout", "build.stderr", "population.txt", binary["filename"]}
    expected_names |= {f"case-{number}.{kind}" for number in range(4) for kind in ("stdout", "stderr")}
    pins = selected["artifacts"]
    require(type(pins) is dict and set(pins) == expected_names and report["artifacts"] == pins, "artifact_population")
    for name, pin in pins.items():
        require(type(pin) is dict and set(pin) == {"sha256", "bytes"}
                and _digest(pin["sha256"]) and type(pin["bytes"]) is int
                and 0 <= pin["bytes"] <= MAX_ARTIFACT, "artifact_pin_shape")
        path = _file(packet, name)
        require(sha(path) == pin["sha256"] and path.stat().st_size == pin["bytes"], "artifact_pin_mismatch:" + name)
    require(pins[binary["filename"]]["sha256"] == binary["sha256"], "binary_pin_mismatch")
    require((packet / "source.diff").read_bytes() == b"", "dirty_source_diff")
    population = (packet / "population.txt").read_text().splitlines()
    require(len(population) == 5 and set(population) == {f"{case}: test" for case in (*CASES, "delegation_lookup_worker")}, "native_test_population")
    require(report.get("declared_cases") == list(CASES), "declared_case_population")
    build = report["build"]
    _finished(build)
    require(build["stdout"] == "build.stdout" and build["stderr"] == "build.stderr", "build_log_binding")
    require(type(build.get("argv")) is list and build["argv"][1:-1] == [
        "test", "--locked", "-p", "atomic-canonical", "--test", "delegation_restart",
        "--no-run", "--message-format=json", "-j",
    ] and type(build["argv"][-1]) is str and build["argv"][-1].isdigit(), "build_command")
    compiler_records = [decode(line.encode()) for line in (packet / "build.stdout").read_text().splitlines()]
    executables = [item["executable"] for item in compiler_records
                   if item.get("reason") == "compiler-artifact"
                   and type(item.get("target")) is dict
                   and type(item.get("profile")) is dict
                   and item.get("target", {}).get("name") == "delegation_restart"
                   and item.get("target", {}).get("kind") == ["test"]
                   and item.get("profile", {}).get("test") is True
                   and type(item.get("executable")) is str]
    require(len(executables) == 1 and Path(executables[0]).name == binary["filename"]
            and sum(item.get("reason") == "build-finished" and item.get("success") is True
                    for item in compiler_records) == 1, "compiler_binary_binding")
    results = report.get("results")
    require(type(results) is list and len(results) == 4 and report.get("passed") is True, "case_population_or_failed")
    worker_pids = set()
    for number, (case, result) in enumerate(zip(CASES, results, strict=True)):
        _finished(result)
        require(result.get("case") == case and result.get("passed") is True, "case_binding")
        require(type(result.get("argv")) is list and len(result["argv"]) == 4
                and result["argv"][0] == executables[0]
                and result["argv"][1:] == ["--exact", case, "--nocapture"], "case_command")
        require(result["stdout"] == f"case-{number}.stdout" and result["stderr"] == f"case-{number}.stderr", "case_log_binding")
        stdout = (packet / result["stdout"]).read_text()
        require(f"test {case} ... ok" in stdout
                and "test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out;" in stdout, "native_test_result")
        observed = [decode(line.removeprefix("ATOMIC_NATIVE_LOOKUP=").encode())
                    for line in stdout.splitlines() if line.startswith("ATOMIC_NATIVE_LOOKUP=")]
        require(observed == result.get("observations"), "stdout_observation_binding")
        _observations(number, observed)
        worker_pids.update(value["pid"] for value in observed)
    return {
        "schema": "probity-atomic-native-receipt/v1", "accepted": True,
        "selection_sha256": selection_sha256, "report_sha256": selected["report_sha256"],
        "source_commit": selected["source_commit"], "binary_sha256": binary["sha256"],
        "reader_sha256": selected["reader_sha256"], "cases": list(CASES),
        "case_count": 4, "worker_observations": 12, "coverage": COVERAGE,
        "observed_worker_pids": sorted(worker_pids), "distinct_worker_pid_count": len(worker_pids),
        "assessment": "Selected retained bytes and native control records are consistent; Atomic was not rerun.",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    describe_parser = commands.add_parser("describe", help="print candidate pins for separate consumer review")
    describe_parser.add_argument("--packet", type=Path, required=True)
    check = commands.add_parser("verify", help="check a separately selected retained packet")
    check.add_argument("--packet", type=Path, required=True)
    check.add_argument("--selection", type=Path, required=True)
    check.add_argument("--selection-sha256", required=True)
    check.add_argument("--output", type=Path, required=True, help="new receipt file outside packet")
    args = parser.parse_args()
    try:
        if args.command == "describe":
            print(json.dumps(describe(args.packet), indent=2, sort_keys=True))
            return 0
        output = _plain(args.output)
        require(not output.is_relative_to(_plain(args.packet)), "output_inside_packet")
        require(output != _plain(args.selection) and not output.exists(), "output_already_exists_or_selection")
        try:
            result = verify(args.packet, args.selection, args.selection_sha256)
        except (ValueError, OSError, KeyError, TypeError, IndexError) as error:
            result = {"schema": "probity-atomic-native-receipt/v1", "accepted": False, "reason": str(error)}
        with output.open("x", encoding="utf-8") as stream:
            stream.write(json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n")
        print(json.dumps(result, sort_keys=True))
        return 0 if result["accepted"] else 1
    except (ValueError, OSError, KeyError, TypeError, IndexError) as error:
        print(json.dumps({"accepted": False, "reason": str(error)}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
